### PR TITLE
build: add codeql analysis

### PR DESCRIPTION
**Pull request by WikiRik**
This PR adds [CodeQL analysis](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql). Config file was generated automatically, but I did remove that it runs on all pushes to main and on a schedule since running it with every PR to main is enough in my opinion.

### CODE REVIEW

**Comment by WikiRik** [comment]
Not sure why I drafted this before. Should be good enough to add. We'll fix the issues that come up in different PRs.
If this works well I'll add this to the main repo as well

**Review by ephys — APPROVED** [review]
This looks good to me. But I think we can remove the `******** NOTE ********` part of the workflow file

**Comment by WikiRik** [comment]
Good point, I've removed all comments since we can easily find them back in the Actions template

**Review by ephys — APPROVED** [review]

**Comment by ephys** [comment]
Good to go :)

> If this works well I'll add this to the main repo as well

Can't wait to see how many alerts we get in the main repo

**Pull request merged**
