### PR TITLE
Improve types.d.ts

### PR DESCRIPTION
**Pull request by arniu**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` pass with this change (including linting)?
- [ ] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### CODE REVIEW

**Comment by ephys** [comment]
Hi, thank you for the PR

Unfortunately I would need a good reason to merge this change. I don't want to declare a global namespace. I think importing the type is cleaner.

**Comment by arniu** [comment]
These types are only referred in migration/seeder scripts. There is no need to import them explicitly.

**Comment by ephys** [comment]
The fact that they're only referred in migrations is the reason why they're imported, instead of declared globally. It doesn't make sense to add something to the global object that is only used in a handful of files

It's also pretty standard https://github.com/ephys/new-sequelize-website/blob/ephys/docusaurus/docusaurus.config.js#L7

**Comment by ephys** [comment]
projects have more than just migrations, so `sequelize-cli` is going to end up in the same package.json as the rest of the project's dependencies.

**Comment by arniu** [comment]
The other source files  are different. 

There may be some dependencies and `import`s already. It's negligible to add a new one.

**Comment by ephys** [comment]
I'm not sure I understand what you mean.

Nonetheless, the reason you gave me is not sufficient to add something to the global object. It's something that should be avoided as much as possible.

**Comment by arniu** [comment]
@ephys 我改用中文，希望你能看懂。

## 会不会破坏已有代码？

`types.d.ts` 是最近加添加的，还没有发布，根本不会破坏已有代码。

## 为什么此处全局类型更合适？

migration 脚本跟其他代码不一样，它可以是某个工程的一部分，也可以是独立的脚本。

此时 `sequelize-cli` 就不再是一个 package，而是 migration 脚本的执行环境。作为上下文，执行环境导出最常见的全局类型，是合理的。

那么 `sequelize-cli` 会不会作为一个 package 使用呢？我看难，它也没导出其他东西。

**Comment by ephys** [comment]
I'm hoping google translate gave me the right translation :)

It's true, this wasn't released yet so it's not a breaking change.

But whether migrations are standalone or not is not really relevant.
We don't have a good reason to declare a global type.
The only scenario where we would declare a global type is to type a global variable. But we don't have any.

It makes sense for libraries like `jest`, `mocha` etc, to do so because they expose their functions (`it`, `description`, `expect`) as globals.

Doing this in sequelize-cli would only impact the typing comment.
`/** @type {import('sequelize-cli').Migration} */`
would become
`/** @type {SequelizeCLI.Migration} */`

It's a few characters shorter but it's not worth declaring a global type.

**Pull request closed without merging**
