### PR TITLE
Enabling babel

### PR DESCRIPTION
**Pull request by xpepermint**
Very simple update that enables es6/es7 support through babel.

### CODE REVIEW

**Comment by fundon** [comment]
CI has failed.

**Comment by xpepermint** [comment]
Well... it actually works - I use the fork on many projects.

**Comment by xpepermint** [comment]
Recreated https://github.com/sequelize/cli/pull/189.

**Comment by fundon** [comment]
Maybe you do not need to create ne PR. 
Rebase the commit in the final.

**Pull request closed without merging**
