### PR TITLE
[Added] Read configuration from config.js if available

### PR DESCRIPTION
**Pull request by sdepold**
This PR makes the CLI read the configuration from `config/config.js` if available. This way it is possible to have dynamic content in the configuration file (e.g. you could read environment variables).

### CODE REVIEW

**Comment by sdepold** [comment]
Fixes https://github.com/sequelize/cli/pull/163

**Comment by bassarisse** [comment]
Just wanted to point out that `fs.existsSync` is currently deprecated ;)

**Comment by sdepold** [comment]
> Just wanted to point out that fs.existsSync is currently deprecated ;)

nooooo! :D Thanks for the hint. I recall reading something about that.

**Comment by sdepold** [comment]
`fs.accessSync(path, fs.R_OK)` is the way to go these days?

**Comment by bassarisse** [comment]
Yes, and we now have to check for exceptions, no more boolean value returned...

**Comment by bassarisse** [comment]
Sorry for the delay, I just tested this, it worked beautifully =)

**Comment by sdepold** [comment]
:cool: Will update the PR to use accessSync for newer node versions and release during the week.

**Comment by sdepold** [comment]
I really have to fix those annoying tests at some point :(

@bassarisse can you review my usage of fs.accessSync ?

**Comment by sdepold** [comment]
Released as v2.0.0

**Comment by bassarisse** [comment]
Good to know! Sorry for not responding, was on vacation.

**Pull request merged**
