### PR TITLE
Adding try/catch block to attempt to get sequelize instance

### PR DESCRIPTION
**Pull request by timrourke**
This relates to closed issue: sequelize db:migrate not working #187

### CODE REVIEW

**Comment by sdepold** [comment]
Closing this in favor of #199

**Comment by sdepold** [comment]
Thanks for your work :)

**Comment by timrourke** [comment]
lol, i was up all night writing that :)

**Comment by sdepold** [comment]
> lol, i was up all night writing that :)

I can imagine :D

**Pull request closed without merging**
