### PR TITLE
Add async configuration support.

### PR DESCRIPTION
**Pull request by wwalser**
Google Cloud's infrastructure doesn't inject metadata into the environment, instead, you have to call an outside service. Because of this, I need a migration solution that offers asynchronous configuration.

This, as I've discovered over the past five hours, is surprisingly difficult primarily because of a combination of:
1. Gulp doesn't support async configuration and doesn't plan to add it, [see Gulp Issue 1505](https://github.com/gulpjs/gulp/issues/1505)
2. The config helper API relies on state that is internal to the module and all calls assume the initialization of that state is synchronous.

To maintain existing behavior, this change takes care to initialize config at the start of all gulp tasks but waits until readConfig is called before logging anything or showing errors.

I'm happy to make the documentation changes if that would be helpful. Would you like this in this PR or a separate one?

### CODE REVIEW

**Comment by wwalser** [comment]
I believe I have the tests passing. I had to remove the `{logging: false}` option from `readConfig`. It was only used in one place, the `version` command.

I'm not sure why, but it was causing problems for a subset of tests. After removing the option, all tests pass.

**Comment by wwalser** [comment]
This passed for me, flaky tests? https://travis-ci.org/wwalser/cli/builds/163213992

**Comment by validkeys** [comment]
Perfect timing. I also need for fetching a decrypted key from an external key management store prior to loading my models.

**Comment by validkeys** [comment]
Any reason we're not merging this one? Would help me out a lot!

**Comment by wwalser** [comment]
I haven't added tests or documentation changes which I think would be reasonable requests by a maintainer before landing the PR. However, I'd like to get at least a nod from a maintainer to know that _if_ I spend time on those, it will get landed.

Maybe I should mention them to get attention. Ping: @felixfbecker or @sdepold

**Comment by felixfbecker** [comment]
Im not a maintainer of the CLI :)

**Comment by wwalser** [comment]
Sry mate, I saw you active in the issues area and noticed "sequelize member" in the header of your comments. Do you know whose attention we should be trying to get perhaps?

Thanks :)

**Comment by wwalser** [comment]
One more try for @sdepold.

**Comment by wwalser** [comment]
Okay, trying a whole new crew. How about @Americas or @sushantdhiman?

**Comment by sushantdhiman** [comment]
Sorry for all this delay @wwalser , While this PR looks good to me generally but I am not familiar with **sequelize/cli** codebase. I will assign this issue to @sdepold and @Americas as they are more invloved with **sequelize/cli** maintenance

**Comment by Americas** [comment]
This PR LGTM too. And I can assure you I will merge this provided everything is good and has tests. You have our blessing :stuck_out_tongue:

**Comment by sdepold** [comment]
You have my entire trust. Go ahead @sushantdhiman :)

**Comment by wwalser** [comment]
I've added migrate and seed tests which use async configuration. Feel free to code review and land when appropriate.

I'd like to understand the NPM release schedule as well since I'm currently using my own branch of these changes in production.

**Comment by wwalser** [comment]
Would you like me to squash before you merge?

**Comment by sushantdhiman** [comment]
Github interface allow squashing so no need. @Americas will merge after review :)

**Comment by wwalser** [comment]
Ping @Americas 

🎱

**Comment by wwalser** [comment]
ahem… may I get this PR landed for Christmas?

🎄🎄🎅🎅🎅🏽🎅🏽🎁🎁

**Comment by wwalser** [comment]
@sushantdhiman PR approved, tests written and passing. Please land.

Thanks!

**Comment by sushantdhiman** [comment]
Thanks for this PR @wwalser , Sorry for this delay

**Pull request merged**
