### PR TITLE
Use node's resolve resolution. Fixes #104

### LINKED ISSUE #104: Problem accessing sequelize cli when installed globally
So from a folder like this c:/Documents/Coding/Example
I have installed globally sequelize-cli with `npm install -g sequelize-cli`, which it did successfully
and i can run sequelize help:init command, no issue
I created another folder c:/Documents/Coding/Test
I try to run sequelize help, it doesn't work this time, I get the following error message:
'Unable to resolve sequelize package in c:/Documents/Coding/Test'

is this an environment variable issue? or something else?
I'm on Windows 7, using Node 0.10.36 CLI: 1.3.1
My Example folder has a few things in it, including, Sequelize installed locally
My Test folder is empty, a brand new project.
Any clues?

### PR DESCRIPTION
**Pull request by carenas**
Tested on ubuntu 14.04 with node 0.10.25 (installed globally in /usr/local/lib/node_modules) and 0.12.7 (installed globally in a nodeenv)

### CODE REVIEW

**Comment by sdepold** [comment]
Tests are broken :(

**Comment by carenas** [comment]
the 2 test cases that are failing seem to be in unrelated code and probably triggered by some environment issue as they are both timeouts.

I am not very familiar with the code base though and considering I wasn't even able to run sequelize before this fix take my comments with a grain of salt

**Comment by sdepold** [comment]
I restarted the tests :)

**Comment by sdepold** [comment]
released as 1.8.2

**Pull request merged**
