### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by ruimarinho**
* findup-sync@0.2.1
  * fs-extra@0.16.3
  * gulp@3.8.10
  * lodash@3.0.1
  * moment@2.9.0
  * yargs@1.3.3
  * gulp-mocha@2.0.0
  * mocha@2.1.0
  * mysql@2.5.4
  * pg@4.2.0
  * pg-hstore@2.3.1
  * through2@0.6.3

### CODE REVIEW

**Comment by sdepold** [comment]
Build is broken :(

**Comment by ruimarinho** [comment]
I'll downgrade to node 0.10 and check it locally then. With io.js sqlite and others do not compile yet :/

**Comment by ruimarinho** [comment]
@sdepold checked with node 0.10, all tests are passing. It was just the cache on Travis. I've had to remove caching from the .travis.yml file since I do not have permission to clear the cache manually. Could you please discard this commit when merging and clear the cache manually?

**Comment by sdepold** [comment]
Thanks for your work :)

**Comment by sdepold** [comment]
Alright! Done. :)

**Comment by ruimarinho** [comment]
Nice, cheers :)

**Pull request closed without merging**
