### PR TITLE
url as option; custom logging function 

### PR DESCRIPTION
**Pull request by PavelPolyakov**
Please, review.

Besides, I have added the Vagrant definition and provision, in order to be able to setup mysql server quickly.

Regards,

### CODE REVIEW

**Comment by sdepold** [comment]
super nice!

**Comment by PavelPolyakov** [comment]
Please, release the new version on npm, when you have free time.

**Comment by sdepold** [comment]
woops i thought i did :(

**Comment by sdepold** [comment]
2.2.0

**Pull request merged**
