### PR TITLE
Adds the argument --es6 in the command migration:create and seed:create

### PR DESCRIPTION
**Pull request by felpin**
The purpose of the PR is to add the option `--es6` to the command `migration:create`.

When executing `migration:create --es6` it will use a skeleton in ES6 format with arrow functions.

This PR resolves issue #482, although it is not a breaking change required for major version. Maybe a future PR can change the default skeleton to be in ES6 format.

This PR may resolve issue #389 if it is a duplicate from #482.

OBS: When executing `migration:create --es6 --coffee`, the argument `--es6` will be ignored. The reason is that the js file would be converted to a coffee file. 'Would' is the correct word here because [js2coffee](https://www.npmjs.com/package/js2coffee) doesn't support ES6 yet (See [issue](https://github.com/js2coffee/js2coffee/issues/449))

### CODE REVIEW

**Comment by felpin** [comment]
I've just realized that there is another skeleton for `seed:create`.

Well... I'll work on this to support `--es6` argument as well.

**Comment by Jadex1** [comment]
What does OBS stand for?

**Comment by felpin** [comment]
Observation

Where I live, it's a common word to use when you want to write something that the reader must pay attention. I didn't know it wasn't usual outside my country.

**Comment by Jadex1** [comment]
Ah, I was trying not to assume anything. What country are you from? I’m also new to Open Source and I didn’t know if it was something specific to the project or not.

- James

**Comment by felpin** [comment]
Does anyone know how to run CI again? The check has failed because
`The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/cli/commit/733ced9e55b48d7aa87cfb964e37a028bc5c95d4

**Pull request closed without merging**
