### PR TITLE
support ES6+ syntax by babel

### PR DESCRIPTION
**Pull request by fundon**
#112

Add `--es6` will be enabled.

### CODE REVIEW

**Comment by fundon** [comment]
I will rebase the commits.

**Comment by sdepold** [comment]
Tests are broken.

**Comment by fundon** [comment]
Okay, I check them.

**Comment by fundon** [comment]
Maby it's just TravisCI's problem.

**Comment by fundon** [comment]
@sdepold 
It was passed.

**Comment by fundon** [comment]
@sdepold 
Currently, I'm use it in my branch.
Example: https://github.com/FuturespaceIO/futurespace/blob/master/.sequelizerc
It's good working.

**Comment by sdepold** [comment]
First of all thanks for your work. I think I will change the template of the migrations tomorrow or just soon. Afterwards you would need to change your templates, too. I would keep this on hold until then ok?

**Comment by fundon** [comment]
Okay, I will follow you.

**Comment by fundon** [comment]
Hi @sdepold Is it done yet?

**Comment by sdepold** [comment]
Alright. I changed the migrations. Can you take a look at the current master and rebase your work?

**Comment by t128** [comment]
would be nice if it would also check for *babel-core/register*

**Pull request closed without merging**
