### PR TITLE
fix: running single seeder is so slow

### LINKED ISSUE #943: sequelize-cli: running single seed file is slow
When I run all the seeds with `sequelize-cli db:seed:all` the command will finish running in under a second. However, if I try to run a single seed file with `sequelize-cli db:seed --seed {file}` it'll take about 10 seconds to run. The terminal output shows me that the seed finishes "migrating" in under .5 seconds but it then just hangs for the other 9.5 seconds.

## What you are doing?
sequelize-cli db:seed --seed {file}

## What do you expect to happen?
I expect the above command to finish quickly, under 1 second

## What is actually happening?
The seeding/migration finishes but the command hangs for about 10 seconds

__Dialect:__ mariadb
__Sequelize CLI version: 6.2.0
__Sequelize version:__ 6.3.5

### PR DESCRIPTION
**Pull request by a60814billy**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `npm run test` pass with this change (including linting)?
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving?
- [ ] Have you added new tests to prevent regressions?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

### Description of change

fixed #943 

#### about test failed
The `npm run test` has 2 faileds.
First one is on prettier (in file `test/support/helpers.js`), but I didn't change this file.
Second one is on `1) [SQLITE] lib/sequelize model:create` -> `attributes` -> `--attributes first_name:string,last_name:string,bio:text,role:enum:{Admin,"Guest User"},reviews:array:text
           exits with exit code 0:`, but this test case also failed in master branch.

I think those test failed is not about my changes.

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]
@sdepold this looks good to me, the tests also pass after rebasing on my fork; https://github.com/WikiRik/cli/actions/runs/1429024655

**Comment by sdepold** [comment]
I wonder which option is turned off that I cannot rebase through the ui

**Comment by a60814billy** [comment]
Hi @sdepold , I'm rebased to latest main branch.

**Pull request merged**
