### PR TITLE
ci: move to github-actions

### PR DESCRIPTION
**Pull request by WikiRik**
### Pull Request check-list

_Please make sure to review and check all of these items:_

- [x] Does `npm run test` pass with this change (including linting)? _Yes*, see https://github.com/WikiRik/cli/actions/runs/1417680810_
- [x] Does the description below contain a link to an existing issue (Closes #[issue]) or a description of the issue you are solving? _Not applicable_
- [x] Have you added new tests to prevent regressions? _Not applicable_
- [x] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)? _Badge in README is updated_

### Description of change

Moving from Travis CI to GitHub Actions, in line with the main repo.

\* = Sometimes the SQLite tests with Node 12 and latest sequelize will fail because of the following error; `Segmentation fault (core dumped)`. This does not happen consistently, so I'm not sure how to deal with it. One example of a failing test can be found [here](https://github.com/WikiRik/cli/actions/runs/1355444593/attempts/1).

### CODE REVIEW

**Comment by WikiRik** [comment]
I believe that GitHub Actions should be enabled first before we can test if this works.

**Comment by WikiRik** [comment]
Well, Github Actions now do the same as Travis. Now just to solve the timeout issue with MySQL.

**Comment by WikiRik** [comment]
@papb can you check this out?
A warning beforehand, the SQLite tests with Node 12 sometimes fail without no real reason. The error given is `Segmentation fault (core dumped)`

**Comment by WikiRik** [comment]
@sdepold I will rebase this today, do you want me to add making releases here as well? Just like is done for the regular sequelize repo

**Comment by sdepold** [comment]
I just found out about this issue today (seems that I have misconfigured my mailbox :)). In short: Yes! Let's move to github actions! will look into it later today!

**Comment by WikiRik** [comment]
No worries, thanks for looking into it!

**Comment by sdepold** [comment]
Amazing stuff. Thanks a bunch!

**Pull request merged**
