### PR TITLE
babel support

### PR DESCRIPTION
**Pull request by xpepermint**

### CODE REVIEW

**Comment by fundon** [comment]
Add `babel` moduel to `package.json`

**Comment by xpepermint** [comment]
Crap... I'm multitasking... let me do this after work ;)

**Comment by sdepold** [comment]
:) Let's see how this works out :)

**Comment by sdepold** [comment]
The tests are sometimes a bit flaky, I will restart them if they are failing.

**Comment by sdepold** [comment]
That could pretty much work :)

**Comment by sdepold** [comment]
Hm something is seriously broken / misbehaving

**Comment by xpepermint** [comment]
@sdepold  Hum... btw... I use this patch in all my apps. What do you suggest?

**Comment by xpepermint** [comment]
@sdepold All tests are passing on my local computer - `319 passing (31m)`.

**Comment by sdepold** [comment]
meh. ok will check

**Comment by xpepermint** [comment]
Hehe, ok ;).

**Comment by sdepold** [comment]
hmmmm weird

**Comment by xpepermint** [comment]
Yeah, it is ;). It should be simple. Hum... how about travis node version or smth?

**Comment by sdepold** [comment]
So it uses node 0.10, which should be fine, no?

**Comment by xpepermint** [comment]
Well... I guess... we already have node 4.+ but it should work. What if you try to change the version for travis?

**Comment by sdepold** [comment]
just merged a PR that enable builds for node 4.0 as well

**Comment by sushantdhiman** [comment]
Closing (PR Cleanup), Open new PR if you wish to continue your work

**Pull request closed without merging**
