### PR TITLE
fixes Bluebird promise warnings

### PR DESCRIPTION
**Pull request by leebenson**
- fixes sequelize/cli/issues/242
- fixes sequelize/cli/issues/247

### CODE REVIEW

**Comment by sdepold** [comment]
👌

**Comment by Americas** [comment]
it fails to fix the warnings, as I said before this issue is not cli related.

But I like this change, promises > callbacks :laughing:

**Comment by leebenson** [comment]
@Americas it fixed them on my end.

**Comment by Americas** [comment]
ahah, I linked to the wrong cli package. My bad!

It does work. But it is strange, since there was no unreturned promise to begin with :laughing:

**Comment by leebenson** [comment]
The issue starts with the gulp task. As @opatut mentioned in #247, running `db:migrate` yielded something close to this:

> Finished 'db:migrate' after 99 ms

... yet the task would continue to run after gulp considered it finished. By returning the `sequelize` chain inside the task and transforming the called `getMigrator` function to use promises, there's now a neat chain for gulp to manage the task.

Bottom line: Always return inside a promise.

**Comment by Americas** [comment]
I'm not questioning the fact that gulp returned before it finished running. Granted you can fix that and at the same time fix the promise warnings, you should also be able to fix the promise warnings without fixing the gulp early finish. And that was what was bothering, but I finally figured it out! saul goodman! :laughing:

**Pull request merged**
