### PR TITLE
addded db:migrate:undo:all to undo all migrations at once

### PR DESCRIPTION
**Pull request by Americas**
Simple task to undo all migrations, instead of going one by one.

### CODE REVIEW

**Comment by sdepold** [comment]
Awesome! Exactly what I was just about to implement :)

**Comment by sdepold** [comment]
Do you think you could try to add some tests for that feature?

**Comment by Americas** [comment]
How do I get your tests to use postgres instead of mysql? I have created a test based on the undo test, it should grab 2 migrations, test if they are applied, run undo:all, and test if they are both gone.

**Comment by sdepold** [comment]
nice :) thank you!

**Comment by sdepold** [comment]
merged and released as 1.5.0

**Pull request closed without merging**
