### PR TITLE
Show original error details

### PR DESCRIPTION
**Pull request by kroleg**
This patch is very useful for debugging errors which happens when you run db:migrate.
Error before (not so user-friendly):
```
ERROR: Validation error
```
Error after (much easier to find what causes it, right?):
```
ERROR: Validation error
Message: could not create unique index "unique_slug". Details: Key (slug)=(dota2-pro-league-1-open-qualifiers) is duplicated.
```

### CODE REVIEW

**Comment by jackycute** [comment]
I had same issue, could this been merged soon?

**Comment by ff-will** [comment]
Oh boy, that would be really helpful!

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/cli/commit/ea837e533921bbc5f45702788a8cc95df50009dc

**Comment by sushantdhiman** [comment]
Extra error message will be printed with `--debug` flag

**Pull request closed without merging**
