### PR TITLE
feat(mode:generate) add enum support

### LINKED ISSUE #550: Enum support
It should be possible to create enum values from `model:create` command

```bash
$ sequelize model:create --name User --attributes opts:enum(x,y,z)
```

### PR DESCRIPTION
**Pull request by mkly**
Add support for `model:generate --name User role:enum:{Admin, Guest}`

Closes #550

### CODE REVIEW

**Comment by mkly** [comment]
Hello!
Thanks for this great tool. I was curious about enum support and discovered that I was not the only one. I took a first pass at it here. I imagine there is somewhere I should also be adding docs for this, so definitely let me know and I'll add them on to this PR. Let me know what I might need to adjust. :jack_o_lantern: 

Best, 
Mike

**Comment by sushantdhiman** [comment]
Looks good, you can add an example here https://github.com/sequelize/cli/blob/master/docs/FAQ.md#how-can-i-generate-a-model

**Comment by mkly** [comment]
@sushantdhiman I updated the FAQ with the additional enum. Thanks for pointing me in the right direction.

**Comment by achacttn** [comment]
Am I crazy or does this cli syntax NOT work at all?

This is what I type into my terminal:

`sequelize model:create --name Customer --attributes id:integer,nameTitle:enum:{Mr,Mrs,Miss,Ms,Dr,Prof},nameFirst:string,nameMiddle:string,nameLast:string`

Result:

`ERROR: Attribute 'nameTitle:enum:Mr' cannot be parsed: Unknown type 'Mr'`

**Comment by mkly** [comment]
Hi @achacttn 
I have a hunch you're shell is modifying it. Try:
```
sequelize model:create --name Customer --attributes 'id:integer,nameTitle:enum:{Mr,Mrs,Miss,Ms,Dr,Prof},nameFirst:string,nameMiddle:string,nameLast:string'
```
or...
```
sequelize model:create --name Customer --attributes id:integer,nameTitle:enum:\{Mr,Mrs,Miss,Ms,Dr,Prof\},nameFirst:string,nameMiddle:string,nameLast:string
```

Unfortunately, that's probably going to confuse a fair amount of people. I'll post an update to the documentation. Thank you for letting me know.

**Comment by botaniQQQ** [comment]
Hello, @mkly 

```
sequelize model:create --name Customer --attributes id:integer,nameTitle:enum:\{Mr,Mrs,Miss,Ms,Dr,Prof\},nameFirst:string,nameMiddle:string,nameLast:string

Sequelize CLI [Node: 10.15.0, CLI: 5.3.0, ORM: 5.0.0-beta.16]

ERROR: Attribute 'nameTitle:enum:\{Mr,Mrs,Miss,Ms,Dr,Prof\}' cannot be parsed: Unknown type '\{Mr,Mrs,Miss,Ms,Dr,Prof\}'
```

**Pull request merged**
