### PR TITLE
adding schema as a recognized storage option (should work for seeders…

### PR DESCRIPTION
**Pull request by jonnolen**
… and migrations)

This would required an update to package.json once PR https://github.com/sequelize/umzug/pull/34 is accepted into umzug.

I do not have a local test environment to run/update tests with.

### CODE REVIEW

**Comment by jonnolen** [comment]
resolves #204

**Comment by sushantdhiman** [comment]
Closing (PR Cleanup), Open new PR if you wish to continue your work

**Comment by wmpay** [comment]
@jonnolen @sushantdhiman mind if I take this on? What needs to be done just fixing tests?

**Comment by sushantdhiman** [comment]
Hi @wmpay , There is already a PR https://github.com/sequelize/cli/pull/635 but we couldn't figure out why tests are failing on Travis. It would be great if you can fix what is bugging CI

**Pull request closed without merging**
