### PR TITLE
Fix small markup typo

### PR DESCRIPTION
**Pull request by jonatasrancan**
Fixing small typo on README

### CODE REVIEW

**Comment by sushantdhiman** [comment]
I think docs are referring to node imports i.e. `require()`, hence the verb `require`d. You can change it something like "file will get imported"

**Comment by Americas** [comment]
I prefer the way it is. It explicitly says that the `.sequelizerc` file is passed to `require`, so that file can be anything that `require` can handle.

**Comment by jonatasrancan** [comment]
hum.....
So after all, it's not a typo, I just got it wrong.

**Comment by jonatasrancan** [comment]
@Americas going to close then. 
ok?

**Pull request closed without merging**
